from enum import StrEnum
class PaymentMethod(StrEnum): CREDIT_CARD="CREDIT_CARD"; DEBIT_CARD="DEBIT_CARD"; UPI="UPI"; CASH="CASH"
class PaymentStatus(StrEnum): INITIATED="INITIATED"; SUCCESS="SUCCESS"; FAILED="FAILED"; PENDING="PENDING"; DEBITED="DEBITED"; REFUND_PENDING="REFUND_PENDING"; REFUNDED="REFUNDED"; DISPUTED="DISPUTED"; RECONCILIATION_REQUIRED="RECONCILIATION_REQUIRED"; PAYMENT_FAILED="PAYMENT_FAILED"
class ApprovalStatus(StrEnum): PENDING="PENDING"; APPROVED="APPROVED"; REJECTED="REJECTED"; MORE_INFORMATION_REQUIRED="MORE_INFORMATION_REQUIRED"; EXECUTED="EXECUTED"; FAILED="FAILED"
class Action(StrEnum): NO_ACTION="NO_ACTION"; WAIT_AND_RECHECK="WAIT_AND_RECHECK"; RECONCILE="RECONCILE"; ESCALATE="ESCALATE"; CREATE_DISPUTE="CREATE_DISPUTE"; SIMULATED_REFUND="SIMULATED_REFUND"; SIMULATED_REVERSAL="SIMULATED_REVERSAL"; REQUEST_MORE_INFORMATION="REQUEST_MORE_INFORMATION"
SENSITIVE_ACTIONS={Action.CREATE_DISPUTE,Action.SIMULATED_REFUND,Action.SIMULATED_REVERSAL}
